config/routes.rb
Co2::Application.routes.draw do
  devise_for :users

  resources :bills do
    get :new_consumptions, :on => :member, :action => :new_consumptions
    post :create_consumptions, :on => :member, :action => :create_consumptions
    post :check_consumptions, :on => :member
  end

  root :to => 'welcome#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    user ||= User.new

    can :read, Bill if ['manager', 'secretary'].include?(user.role)

    can [:new, :create], Bill if user.role == 'secretary'

    can [:edit, :update, :new_consumptions, :create_consumptions], Bill, :author_id => user.id, :checker_id => nil if user.role == "secretary"

    if user.role == 'manager'
      can [:check_consumptions], Bill do |bill|
        bill.checker_id == nil && !bill.consumption_ids.empty?
      end
    end

    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/bill.rb
class Bill < ActiveRecord::Base
  attr_accessible :consumption_unit, :name, :period_start, :period_stop, :time_unit, :consumptions_attributes

  has_many :consumptions

  accepts_nested_attributes_for :consumptions

  belongs_to :author, :class_name => 'User'

  belongs_to :checker, :class_name => 'User'

  @@time_units = {'Days' => 'D', 'Weeks' => 'W', 'Months' => 'M', 'Years' => 'Y'}

  before_save :end_of_month

  def self.time_units
    @@time_units
  end

  validates_presence_of :name, :period_start, :period_stop, :consumption_unit, :time_unit
  validates_inclusion_of :time_unit, :in => @@time_units.values
  validates_datetime :period_stop, :on_or_after => :period_start, :after_message => 'Must be after Period start'

  def num_intervals
    case time_unit
    when 'D'
      ((period_stop + 1) - period_start).to_i
    when 'W'
      ((period_stop - period_start) / 7).ceil.to_i
    when 'M'
      (period_stop.year*12+(period_stop.month + 1)) - (period_start.year*12+period_start.month).to_i
    when 'Y'
      ((period_stop.year + 1) - period_start.year).to_i
    end
  end

  def singularized_time_unit
    @@time_units.invert[time_unit].singularize
  end

  private

  def end_of_month
    self.period_stop = period_stop.end_of_month
  end

end

app/models/consumption.rb
class Consumption < ActiveRecord::Base
  belongs_to :bill
  attr_accessible :sequence_number, :value

  validates_presence_of :sequence_number, :value

  def interval
    "#{bill.singularized_time_unit} #{sequence_number}"
  end

  def interval_value
    "#{interval} (#{value} #{bill.consumption_unit})"
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  check_authorization :unless => :devise_controller?

  rescue_from CanCan::AccessDenied do |exception|
    if user_signed_in?
      redirect_to root_url, :alert => exception.message
    else
      authenticate_user!
    end
  end


end

app/controllers/bills_controller.rb
class BillsController < ApplicationController

  respond_to :html

  before_filter :load_bill, :except => [:index, :create, :new]
  authorize_resource


  def index
    @bills = Bill.order('checker_id DESC, created_at ASC').includes(:consumptions)
    respond_with @bills
  end

  def show
  end

  def new
    @bill = Bill.new
    respond_with(@bill)
  end

  def create
    @bill = Bill.new(params[:bill])
    @bill.author = current_user 
    if @bill.save
      flash[:notice] = "Bill succesfully added"
      location = new_consumptions_bill_url(@bill)
    end
    respond_with(@bill, :location => location)
  end

  def edit
    respond_with(@bill)
  end

  def update
    if(@bill.update_attributes(params[:bill]))
       flash[:notice] = "Successfully edited bill"
    end
    respond_with(@bill, :location => bills_url)
  end

  def new_consumptions
    if @bill.consumptions.empty?
      1.upto(@bill.num_intervals) do |counter|
        @bill.consumptions.build(:sequence_number => counter)
      end
    end
    respond_with(@bill)
  end

  def create_consumptions
    respond_with(@bill) do |format|
      if @bill.update_attributes(params[:bill])
        flash[:notice] = 'Successfully stored consumptions'
        format.html { redirect_to bills_path }
      else
        format.html { render action: "new_consumptions" }
      end
    end
  end

  def check_consumptions
    params[:bill][:consumption_ids].pop
    puts params[:bill][:consumption_ids].inspect
    respond_with(@bill) do |format|
      if(@bill.consumption_ids == params[:bill][:consumption_ids].map{|x| x.to_i})
        @bill.checker = current_user
        @bill.save
        flash[:notice] = "Bill succesfully checked"
        format.html { redirect_to bills_path }
      else
        flash[:error] = "All consumptions must be checked in order to check the bill"
        format.html { render action: 'show' }
      end
    end
  end

  private

  def load_bill
    @bill = Bill.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  skip_authorization_check

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/bills/_form.html.erb
<%= simple_form_for @bill, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :name %>
  <%= f.input :period_start, :as => :date , :order => [:month, :year], :discard_day => true %>
  <%= f.input :period_stop, :as => :date , :order => [:month, :year], :discard_day => true %>
  <%= f.input :consumption_unit %>
  <%= f.input :time_unit, :as => :radio_buttons, :collection => Bill.time_units %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                bills_path, :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/bills/edit.html.erb
<%- model_class = Bill -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/bills/index.html.erb
<%- model_class = Bill -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:period_start) %></th>
      <th><%= model_class.human_attribute_name(:period_stop) %></th>
      <th><%= model_class.human_attribute_name(:consumption_unit) %></th>
      <th><%= model_class.human_attribute_name(:time_unit) %></th>
      <th><%= model_class.human_attribute_name(:author_id) %></th>
      <th><%= model_class.human_attribute_name(:checker_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @bills.each do |bill| %>
      <tr class="<%= (bill.consumption_ids.empty? ? 'warning' : (!bill.checker_id.nil? ? 'success' : ''))  %>">
        <td><%= link_to bill.id, bill_path(bill) %></td>
        <td><%= bill.name %></td>
        <td><%= bill.period_start.to_formatted_s(:month_and_year) %></td>
        <td><%= bill.period_stop.to_formatted_s(:month_and_year) %></td>
        <td><%= bill.consumption_unit %></td>
        <td><%= Bill.time_units.invert[bill.time_unit] %></td>
        <td><%= bill.author.email %></td>
        <td><%= bill.checker.nil? ? 'Not checked' : bill.checker.email %></td>
        <td><%= bill.created_at.to_formatted_s(:short) %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")), edit_bill_path(bill), :class => 'btn btn-mini' if can?(:edit, bill) %>
          <%= link_to('Consumptions', new_consumptions_bill_path(bill), :class => 'btn btn-mini') if can?(:new_consumptions, bill) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")), new_bill_path, :class => 'btn btn-primary' if can?(:new, Bill) %>

app/views/bills/new.html.erb
<%- model_class = Bill -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/bills/new_consumptions.html.erb
<%= simple_form_for @bill, :url => create_consumptions_bill_path, :method => :post, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.simple_fields_for :consumptions do |builder| %>
    <%= builder.input :value, :label => "#{@bill.singularized_time_unit} #{builder.object.sequence_number}", :wrapper => :append do %>
      <%= builder.input_field :value %><span class="add-on"><%= @bill.consumption_unit %></span>
    <% end %>
    <%= builder.input :sequence_number, :as => :hidden %>
  <% end %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                bills_path, :class => 'btn' %>
  </div>
<% end %>

app/views/bills/show.html.erb
<%- model_class = Bill -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @bill.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:period_start) %>:</strong></dt>
  <dd><%= @bill.period_start.to_formatted_s(:month_and_year) %></dd>
  <dt><strong><%= model_class.human_attribute_name(:period_stop) %>:</strong></dt>
  <dd><%= @bill.period_stop.to_formatted_s(:month_and_year) %></dd>
  <dt><strong><%= model_class.human_attribute_name(:consumption_unit) %>:</strong></dt>
  <dd><%= @bill.consumption_unit %></dd>
  <dt><strong><%= model_class.human_attribute_name(:time_unit) %>:</strong></dt>
  <dd><%= Bill.time_units.invert[@bill.time_unit] %></dd>
  <dt><strong><%= model_class.human_attribute_name(:author_id) %>:</strong></dt>
  <dd><%= @bill.author.email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:checker_id) %>:</strong></dt>
  <dd><%= @bill.checker.nil? ? 'Not checked' : @bill.checker.email %></dd>
</dl>

<% if can? :check_consumptions, @bill %>
  <%= simple_form_for @bill, :method => :post, :html => {:class => 'form-horizontal'}, :url => check_consumptions_bill_path, :method => :post do |f| %>
    <%= f.input :consumption_ids, :collection => @bill.consumptions, :as => :check_boxes, :checked => (params[:bill].nil? ? false : params[:bill][:consumption_ids]), :label_method => :interval_value, :include_blank => false, :label => 'Consumptions' %>
    <div class="form-actions">
      <%= f.button :submit, :class => 'btn-primary', :value => 'Check bill' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")), bills_path, :class => 'btn' %>
    </div>
  <% end %>
<% elsif !@bill.consumption_ids.empty? %>
  <h4>Consumptions</h4>
  <table class="table table-striped">
    <th>Date interval</th>
    <th>Value</th>
    <% @bill.consumptions.each do |consumption| %>
      <tr>
        <td><%= consumption.interval %></td>
        <td><%= consumption.value %></td>
      </tr>
    <% end %>
  </table>
<% else %>
  <p class="text-warning">Consumptions have not been added yet.</p>
<% end %>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")), bills_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")), edit_bill_path(@bill), :class => 'btn' if can?(:edit, @bill) %>
  <%= link_to 'Consumptions', new_consumptions_bill_path(@bill), :class => 'btn' if can?(:new_consumptions, @bill) %>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
	<div class="alert alert-<%= name == :notice ? "success" : "error" %>">
		<a class="close" data-dismiss="alert">&#215;</a>
		<%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
	</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Co2" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'images/favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <%= link_to 'Co2', root_path, :class => 'brand' %>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to "Bills", bills_path %></li>
              <% if user_signed_in? %>
                <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %>  </li>
              <% else %>
                <li><%= link_to('Login', new_user_session_path) %> </li>
              <% end %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
        <div class="row">
          <div class="span12">
            <%= render 'layouts/messages' %>
             <%= yield %>
          </div>
        </div><!--/row-->

      <footer>
        <p>&copy; CO2 2012</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/welcome/index.html.erb
<div class="hero-unit">
  <h1>Bills</h1>
  <p>In this application you can enter bills as a secretary or check bills as a manager! You can also see all bills that have been inserted, and based on the color of a row you can see wether a <span class="text-success">bill has been checked</span>, is waiting to be checked or <span class="text-warning">requires additional data</span>.</p>
  <p>
  <%= link_to 'Bills page', bills_path, :class => 'btn btn-primary btn-large' %>
  </p>
</div>